version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # volume to persist data
      - postgres:/var/lib/postgresql/data
      # init scripts directory
      # - ./init.sql:/docker-initdb.d
      # init script
      # - ./init.sql:/docker-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mydomain.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin: